[package]
name = "mzdata-converter"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[profile.release]
lto = "thin"
codegen-units = 1

[dependencies]
mzdata = { version = "0.63", default-features = false, features = ["mzml", "thermo", "bruker_tdf", "parallelism", "nalgebra", "zlib-rs", "mgf"] }
clap = { version = "4", features = ["derive"] }
glob = "0.3"
indicatif = "0.17"
rayon = "1"
mimalloc = "0.1"
libloading = "0.8"
rusqlite = "0.31"
timsrust = { version = "0.4", features = ["tdf"] }
anyhow = "1"
log = "0.4"
env_logger = "0.11"

[dev-dependencies]
tempfile = "3"
